#!/usr/bin/env python3
"""Fail when a dependency is pinned both in project.dependencies and in
[tool.uv] constraint-dependencies.

Such a dependency has two versions in one file and only one of them is visible to
Renovate: the pep621 manager reads project.dependencies but not the constraint list,
which is regenerated from the Airflow constraint file by update_airflow_constraints.sh.
Renovate would keep proposing a bump uv cannot resolve.

The fix is to drop the specifier from project.dependencies and let the constraint
decide, or to remove the declaration if the dependency is only transitive.
"""

import re
import sys
import tomllib
from pathlib import Path

PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def name_of(requirement: str) -> str:
    return re.split(r"[=<>!~\[;]", requirement)[0].strip().lower().replace("_", "-")


def main() -> int:
    config = tomllib.loads(PYPROJECT.read_text())
    constraints = {
        name_of(c): c
        for c in config.get("tool", {}).get("uv", {}).get("constraint-dependencies", [])
    }

    overlap = [
        (dep, constraints[name_of(dep)])
        for dep in config.get("project", {}).get("dependencies", [])
        if name_of(dep) in constraints and re.search(r"[=<>!~]", dep)
    ]

    if not overlap:
        return 0

    print(f"❌ {PYPROJECT.name}: pinned in both project.dependencies and constraint-dependencies")
    for dep, constraint in overlap:
        print(f"   {dep}  <->  {constraint}")
    print("\nDrop the specifier from project.dependencies: the constraint owns the version,")
    print("and it is regenerated by helpers/update_airflow_constraints.sh.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
