version = 3.11.0
runner.dialect = scala212

maxColumn = 120
rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
newlines.implicitParamListModifierPrefer = before
rewrite.trailingCommas.style = always
